In [96]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [97]:
df = pd.read_csv("googleplaystore.csv")

In [98]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,07-Jan-18,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,01-Aug-18,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,08-Jun-18,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [99]:
df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [100]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [101]:
df.isnull().count()

App               10841
Category          10841
Rating            10841
Reviews           10841
Size              10841
Installs          10841
Type              10841
Price             10841
Content Rating    10841
Genres            10841
Last Updated      10841
Current Ver       10841
Android Ver       10841
dtype: int64

In [102]:
print(df.describe())

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [103]:
df.duplicated().sum()

483

In [104]:
df.drop_duplicates(inplace=True)

In [105]:
df.duplicated().sum()

0

In [106]:
missing_val = df.isnull()
missing_val

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [107]:
df.Reviews.unique()

array(['159', '967', '87510', ..., '603', '1195', '398307'], dtype=object)

In [108]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None

In [109]:
def clean(x):
    if "M" in x:
        return float(x[:-1])*1024

In [110]:
df.Size = df["Size"].apply(clean)

In [111]:
df.Size.head()

0    19456.0
1    14336.0
2     8908.8
3    25600.0
4     2867.2
Name: Size, dtype: float64

In [112]:
df.Installs.dropna(inplace=True)

In [113]:
def clean_1(x):
    if "+" in x:
        return float(x[:-1].replace(",",""))

In [114]:
df["Installs"]=df["Installs"].apply(clean_1)

In [115]:
df.Installs.head()

0       10000.0
1      500000.0
2     5000000.0
3    50000000.0
4      100000.0
Name: Installs, dtype: float64

In [116]:
def clean_2(x):
    if "and up" in str(x):
        return x[:-6]

In [117]:
df["Android Ver"]=df["Android Ver"].apply(clean_2)

In [118]:
df["Android Ver"].head()

0    4.0.3
1    4.0.3
2    4.0.3
3      4.2
4      4.4
Name: Android Ver, dtype: object

In [119]:
(df.isna().sum()/df.shape[0])*100

App                0.000000
Category           0.000000
Rating            14.143657
Reviews            0.000000
Size              17.783356
Installs           0.019309
Type               0.009654
Price              0.000000
Content Rating     0.009654
Genres             0.000000
Last Updated       0.000000
Current Ver        0.077235
Android Ver       11.903842
dtype: float64

In [120]:
df["Android Ver"].fillna(df["Android Ver"].mode()[0], inplace=True)

C:\Users\ragha\AppData\Local\Temp\ipykernel_13316\793320667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Android Ver"].fillna(df["Android Ver"].mode()[0], inplace=True)

In [121]:
df.Rating.unique()

array([ 4.1,  3.9,  4.7,  4.5,  4.3,  4.4,  3.8,  4.2,  4.6,  3.2,  4. ,
        nan,  4.8,  4.9,  3.6,  3.7,  3.3,  3.4,  3.5,  3.1,  5. ,  2.6,
        3. ,  1.9,  2.5,  2.8,  2.7,  1. ,  2.9,  2.3,  2.2,  1.7,  2. ,
        1.8,  2.4,  1.6,  2.1,  1.4,  1.5,  1.2, 19. ])

In [122]:
df[df.loc[:,"Rating"]>5].index

Index([10472], dtype='int64')

In [123]:
df.drop([10472],inplace=True)

In [124]:
df.Rating.fillna(df.Rating.mean(),inplace = True)

C:\Users\ragha\AppData\Local\Temp\ipykernel_13316\1546502635.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Rating.fillna(df.Rating.mean(),inplace = True)

In [132]:
def detect_out(x):
    out=[]
    Q1=x.quantile(.25)
    Q3=x.quantile(.75)
    IQR=Q3-Q1
    upper=Q3+(1.5*IQR)
    lower=Q1-(1.5*IQR)
    for i in x:
        if i>upper or i < lower:
            out.append(i)
    return out

In [134]:
detect_out(df.Size)

[74752.0,
 78848.0,
 71680.0,
 86016.0,
 99328.0,
 77824.0,
 77824.0,
 79872.0,
 73728.0,
 78848.0,
 71680.0,
 95232.0,
 80896.0,
 102400.0,
 69632.0,
 80896.0,
 77824.0,
 95232.0,
 79872.0,
 96256.0,
 74752.0,
 78848.0,
 101376.0,
 97280.0,
 102400.0,
 81920.0,
 77824.0,
 77824.0,
 75776.0,
 99328.0,
 70656.0,
 76800.0,
 100352.0,
 79872.0,
 99328.0,
 87040.0,
 79872.0,
 70656.0,
 76800.0,
 71680.0,
 101376.0,
 77824.0,
 75776.0,
 70656.0,
 83968.0,
 98304.0,
 101376.0,
 101376.0,
 89088.0,
 99328.0,
 76800.0,
 73728.0,
 71680.0,
 79872.0,
 75776.0,
 99328.0,
 77824.0,
 102400.0,
 87040.0,
 89088.0,
 72704.0,
 74752.0,
 97280.0,
 79872.0,
 100352.0,
 87040.0,
 102400.0,
 88064.0,
 81920.0,
 80896.0,
 89088.0,
 93184.0,
 97280.0,
 95232.0,
 83968.0,
 101376.0,
 93184.0,
 87040.0,
 82944.0,
 83968.0,
 100352.0,
 78848.0,
 101376.0,
 98304.0,
 98304.0,
 83968.0,
 71680.0,
 86016.0,
 70656.0,
 75776.0,
 93184.0,
 94208.0,
 71680.0,
 95232.0,
 93184.0,
 99328.0,
 95232.0,
 84992.0,
 101376.0,
 82944.0,
 75776.0,
 77824.0,
 99328.0,
 100352.0,
 71680.0,
 70656.0,
 89088.0,
 101376.0,
 83968.0,
 96256.0,
 98304.0,
 76800.0,
 75776.0,
 99328.0,
 79872.0,
 73728.0,
 79872.0,
 76800.0,
 71680.0,
 101376.0,
 101376.0,
 71680.0,
 90112.0,
 83968.0,
 97280.0,
 76800.0,
 101376.0,
 76800.0,
 79872.0,
 102400.0,
 99328.0,
 71680.0,
 78848.0,
 98304.0,
 71680.0,
 101376.0,
 87040.0,
 82944.0,
 80896.0,
 96256.0,
 93184.0,
 93184.0,
 81920.0,
 79872.0,
 84992.0,
 83968.0,
 79872.0,
 96256.0,
 95232.0,
 78848.0,
 70656.0,
 74752.0,
 101376.0,
 69632.0,
 93184.0,
 99328.0,
 97280.0,
 84992.0,
 79872.0,
 71680.0,
 86016.0,
 94208.0,
 76800.0,
 73728.0,
 84992.0,
 99328.0,
 94208.0,
 84992.0,
 93184.0,
 72704.0,
 97280.0,
 102400.0,
 69632.0,
 70656.0,
 99328.0,
 73728.0,
 71680.0,
 75776.0,
 84992.0,
 70656.0,
 88064.0,
 77824.0,
 87040.0,
 91136.0,
 77824.0,
 69632.0,
 100352.0,
 83968.0,
 75776.0,
 90112.0,
 86016.0,
 97280.0,
 83968.0,
 82944.0,
 88064.0,
 72704.0,
 81920.0,
 87040.0,
 97280.0,
 100352.0,
 72704.0,
 91136.0,
 79872.0,
 98304.0,
 75776.0,
 99328.0,
 75776.0,
 77824.0,
 71680.0,
 74752.0,
 87040.0,
 101376.0,
 94208.0,
 71680.0,
 96256.0,
 93184.0,
 82944.0,
 84992.0,
 98304.0,
 102400.0,
 96256.0,
 100352.0,
 99328.0,
 79872.0,
 75776.0,
 75776.0,
 91136.0,
 70656.0,
 75776.0,
 80896.0,
 91136.0,
 80896.0,
 96256.0,
 89088.0,
 76800.0,
 76800.0,
 98304.0,
 99328.0,
 100352.0,
 72704.0,
 79872.0,
 89088.0,
 86016.0,
 83968.0,
 77824.0,
 93184.0,
 70656.0,
 72704.0,
 73728.0,
 97280.0,
 98304.0,
 95232.0,
 84992.0,
 95232.0,
 69632.0,
 98304.0,
 75776.0,
 102400.0,
 97280.0,
 101376.0,
 71680.0,
 101376.0,
 98304.0,
 86016.0,
 101376.0,
 101376.0,
 90112.0,
 89088.0,
 79872.0,
 77824.0,
 81920.0,
 73728.0,
 80896.0,
 100352.0,
 69632.0,
 93184.0,
 98304.0,
 98304.0,
 101376.0,
 90112.0,
 93184.0,
 101376.0,
 83968.0,
 94208.0,
 75776.0,
 88064.0,
 70656.0,
 101376.0,
 93184.0,
 91136.0,
 69632.0,
 87040.0,
 77824.0,
 81920.0,
 82944.0,
 101376.0,
 101376.0,
 101376.0,
 81920.0,
 102400.0,
 70656.0,
 92160.0,
 90112.0,
 76800.0,
 74752.0,
 98304.0,
 74752.0,
 83968.0,
 102400.0,
 71680.0,
 93184.0,
 101376.0,
 92160.0,
 73728.0,
 87040.0,
 83968.0,
 81920.0,
 92160.0,
 72704.0,
 71680.0,
 97280.0,
 95232.0,
 71680.0,
 71680.0,
 69632.0,
 94208.0,
 79872.0,
 70656.0,
 101376.0,
 93184.0,
 79872.0,
 87040.0,
 93184.0,
 83968.0,
 77824.0,
 99328.0,
 102400.0,
 74752.0,
 102400.0,
 89088.0,
 69632.0,
 82944.0,
 91136.0,
 83968.0,
 84992.0,
 81920.0,
 89088.0,
 88064.0,
 77824.0,
 94208.0,
 101376.0,
 71680.0,
 95232.0,
 97280.0,
 98304.0,
 91136.0,
 94208.0,
 95232.0,
 69632.0,
 73728.0,
 87040.0,
 96256.0,
 95232.0,
 73728.0,
 91136.0,
 90112.0,
 100352.0,
 98304.0,
 74752.0,
 75776.0,
 70656.0,
 100352.0,
 100352.0,
 81920.0,
 101376.0,
 77824.0,
 79872.0,
 102400.0,
 93184.0,
 98304.0,
 94208.0,
 101376.0,
 79872.0,
 99328.0,
 96256.0,
 84992.0,
 90112.0,
 100352.0,
 89088.0,
 75776.0,
 78848.0,
 87040.0,
 87040.0,
 70656.0,
 90112.0,
 71680.0,
 90112.0,
 69632.0,
 78848.0,
 90112.0,
 71680.0,
 90112.0,
 98304.0,
 73728.0,
 96256.0,
 69632.0,
 82944.0,
 74752.0,
 73728.0,
 97280.0,
 93184.0,
 90112.0,
 94208.0,
 93184.0,
 93184.0,
 73728.0,
 98304.0,
 81920.0,
 83968.0,
 77824.0,
 78848.0,
 82944.0,
 102400.0,
 87040.0,
 96256.0,
 101376.0,
 89088.0,
 92160.0,
 93184.0,
 89088.0,
 71680.0,
 99328.0,
 94208.0,
 88064.0,
 72704.0,
 79872.0,
 71680.0,
 98304.0,
 77824.0,
 98304.0,
 82944.0,
 97280.0,
 69632.0,
 81920.0,
 86016.0,
 102400.0,
 96256.0,
 97280.0,
 98304.0,
 72704.0,
 80896.0,
 74752.0,
 72704.0,
 98304.0,
 80896.0,
 100352.0,
 101376.0,
 94208.0,
 102400.0,
 73728.0,
 71680.0,
 92160.0,
 101376.0,
 101376.0,
 101376.0,
 96256.0,
 83968.0,
 87040.0,
 101376.0,
 78848.0,
 70656.0,
 69632.0,
 101376.0,
 80896.0,
 74752.0,
 90112.0,
 77824.0,
 79872.0,
 92160.0,
 75776.0,
 94208.0,
 84992.0,
 100352.0,
 70656.0,
 78848.0,
 74752.0,
 84992.0,
 74752.0,
 71680.0,
 70656.0,
 77824.0,
 72704.0,
 73728.0,
 74752.0,
 94208.0,
 87040.0,
 78848.0,
 86016.0,
 95232.0,
 95232.0,
 90112.0,
 73728.0,
 73728.0,
 70656.0,
 98304.0,
 83968.0,
 70656.0,
 97280.0,
 97280.0,
 95232.0,
 101376.0,
 69632.0,
 72704.0,
 69632.0,
 72704.0,
 98304.0,
 72704.0,
 77824.0,
 80896.0,
 91136.0,
 76800.0,
 99328.0,
 70656.0,
 96256.0,
 96256.0,
 101376.0,
 88064.0,
 70656.0,
 73728.0,
 76800.0,
 73728.0,
 86016.0,
 79872.0,
 82944.0,
 83968.0]